name: flutter_loc
description: flutter_loc simplifies localization in Flutter by automating string parsing and offering quick multilingual support.
version: 0.2.4
repository: https://github.com/micazi/flutter_loc

environment:
  sdk: ^3.6.0

dependencies:
  darted_cli: ^0.1.21

dev_dependencies:
  lints: ^5.1.1

executables:
  flutter_loc:
